/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SharedMemoryHandle {
  name: string
  size: number
  buffer: Uint8Array
}
export declare function nativeVersion(): string
export declare function createSharedMemory(size: number): SharedMemoryHandle
export declare function closeSharedMemory(name: string): boolean
