/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class NativeGameBoy {
  constructor()
  /** Load a ROM file. Can be called multiple times to switch games. */
  loadRom(romData: Uint8Array, sramData?: Uint8Array | undefined | null, isDmg?: boolean | undefined | null): void
  /** Advance the emulator by one frame (≈16.67ms). Also pushes audio if enabled. */
  tick(): void
  /**
   * Get the current frame buffer as RGB pixel data.
   * Game Boy screen is 160x144 pixels = 69,120 bytes (3 bytes per pixel).
   */
  getFrameBuffer(): Uint8Array
  /** Press a button (0-7). */
  pressButton(button: number): void
  /** Release a button (0-7). */
  releaseButton(button: number): void
  /** Enable or disable audio output. Returns true if audio is available. */
  setAudioEnabled(enabled: boolean): boolean
  /** Whether the cartridge has battery-backed RAM. */
  hasBattery(): boolean
  /** Get the battery-backed SRAM data, if present. */
  getSram(): Uint8Array | null
  /** Set the battery-backed SRAM data. */
  setSram(data: Uint8Array): void
  /** Save SRAM to the .sav file on disk. */
  saveSramToFile(): void
  /** Save the full emulator state as compressed bytes. */
  saveState(): Uint8Array
  /** Load a full emulator state from compressed bytes. */
  loadState(data: Uint8Array): void
  /** Get the game title from the cartridge header. */
  gameTitle(): string
  /** Whether the emulator is in DMG (original Game Boy) mode. */
  getIsDmg(): boolean
  /** Get an audio warning message if audio was requested but unavailable. */
  getAudioWarning(): string | null
  /** Clean up resources. */
  dispose(): void
}
